#pragma once
/* myOS Win32 SDK - winnt.h */
#include "windef.h"

#ifndef ACCESS_MASK
#define ACCESS_MASK DWORD
#endif


#ifndef GENERIC_READ
#define GENERIC_READ     0x80000000u
#define GENERIC_WRITE    0x40000000u
#define GENERIC_EXECUTE  0x20000000u
#define GENERIC_ALL      0x10000000u
#endif

typedef struct _GENERIC_MAPPING {
    ACCESS_MASK GenericRead;
    ACCESS_MASK GenericWrite;
    ACCESS_MASK GenericExecute;
    ACCESS_MASK GenericAll;
} GENERIC_MAPPING, *PGENERIC_MAPPING;


#define STANDARD_RIGHTS_READ    READ_CONTROL
#define STANDARD_RIGHTS_WRITE   READ_CONTROL
#define STANDARD_RIGHTS_EXECUTE READ_CONTROL
#define STANDARD_RIGHTS_ALL     0x001f0000u

#define SECURITY_NULL_SID_AUTHORITY        {0,0,0,0,0,0}
#define SECURITY_WORLD_SID_AUTHORITY       {0,0,0,0,0,1}
#define SECURITY_LOCAL_SID_AUTHORITY       {0,0,0,0,0,2}
#define SECURITY_NT_AUTHORITY              {0,0,0,0,0,5}
#define SECURITY_MANDATORY_LABEL_AUTHORITY {0,0,0,0,0,16}

#define SECURITY_NULL_RID                  0x00000000u
#define SECURITY_WORLD_RID                 0x00000000u
#define SECURITY_LOCAL_RID                 0x00000000u
#define SECURITY_LOCAL_SYSTEM_RID          0x00000012u
#define SECURITY_BUILTIN_DOMAIN_RID        0x00000020u
#define DOMAIN_ALIAS_RID_ADMINS            0x00000220u

#define SID_REVISION                       1u
#define SID_MAX_SUB_AUTHORITIES            8u
#define SECURITY_MAX_SID_SIZE              (sizeof(SID))

typedef struct _SID_IDENTIFIER_AUTHORITY {
    BYTE Value[6];
} SID_IDENTIFIER_AUTHORITY, *PSID_IDENTIFIER_AUTHORITY;

typedef struct _SID {
    BYTE Revision;
    BYTE SubAuthorityCount;
    SID_IDENTIFIER_AUTHORITY IdentifierAuthority;
    DWORD SubAuthority[SID_MAX_SUB_AUTHORITIES];
} SID, *PISID, *PSID;

typedef WORD SECURITY_DESCRIPTOR_CONTROL, *PSECURITY_DESCRIPTOR_CONTROL;
typedef DWORD SECURITY_INFORMATION, *PSECURITY_INFORMATION;
#define OWNER_SECURITY_INFORMATION 0x00000001u
#define GROUP_SECURITY_INFORMATION 0x00000002u
#define DACL_SECURITY_INFORMATION  0x00000004u
#define SACL_SECURITY_INFORMATION  0x00000008u
#define SE_OWNER_DEFAULTED       0x0001u
#define SE_GROUP_DEFAULTED       0x0002u
#define SE_DACL_PRESENT          0x0004u
#define SE_DACL_DEFAULTED        0x0008u
#define SE_SACL_PRESENT          0x0010u
#define SE_SACL_DEFAULTED        0x0020u
#define SE_DACL_AUTO_INHERIT_REQ 0x0100u
#define SE_SACL_AUTO_INHERIT_REQ 0x0200u
#define SE_DACL_AUTO_INHERITED   0x0400u
#define SE_SACL_AUTO_INHERITED   0x0800u
#define SE_DACL_PROTECTED        0x1000u
#define SE_SACL_PROTECTED        0x2000u
#define SE_SELF_RELATIVE         0x8000u

#define SECURITY_DESCRIPTOR_REVISION        1u
#define SECURITY_DESCRIPTOR_REVISION1       1u

typedef struct _ACL {
    BYTE AclRevision;
    BYTE Sbz1;
    WORD AclSize;
    WORD AceCount;
    WORD Sbz2;
} ACL, *PACL;

#define ACL_REVISION             2u
#define ACL_REVISION_DS          4u

typedef struct _ACE_HEADER {
    BYTE AceType;
    BYTE AceFlags;
    WORD AceSize;
} ACE_HEADER, *PACE_HEADER;

#define ACCESS_ALLOWED_ACE_TYPE  0x00u
#define ACCESS_DENIED_ACE_TYPE   0x01u

#define OBJECT_INHERIT_ACE       0x01u
#define CONTAINER_INHERIT_ACE    0x02u
#define NO_PROPAGATE_INHERIT_ACE 0x04u
#define INHERIT_ONLY_ACE         0x08u
#define INHERITED_ACE            0x10u

typedef struct _ACCESS_ALLOWED_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} ACCESS_ALLOWED_ACE, *PACCESS_ALLOWED_ACE;

typedef struct _ACCESS_DENIED_ACE {
    ACE_HEADER Header;
    ACCESS_MASK Mask;
    DWORD SidStart;
} ACCESS_DENIED_ACE, *PACCESS_DENIED_ACE;

typedef struct _SECURITY_DESCRIPTOR {
    BYTE Revision;
    BYTE Sbz1;
    SECURITY_DESCRIPTOR_CONTROL Control;
    PSID Owner;
    PSID Group;
    PACL Sacl;
    PACL Dacl;
} SECURITY_DESCRIPTOR, *PISECURITY_DESCRIPTOR, *PSECURITY_DESCRIPTOR;

#define ACCESS_SYSTEM_SECURITY   0x01000000u
#define MAXIMUM_ALLOWED          0x02000000u

#define DELETE                   0x00010000u
#define READ_CONTROL             0x00020000u
#define WRITE_DAC                0x00040000u
#define WRITE_OWNER              0x00080000u
#define SYNCHRONIZE              0x00100000u
#define STANDARD_RIGHTS_REQUIRED 0x000f0000u

#define PAGE_READONLY   0x02u
#define PAGE_READWRITE  0x04u

#define FILE_MAP_WRITE      0x0002u
#define FILE_MAP_READ       0x0004u
#define FILE_MAP_ALL_ACCESS (FILE_MAP_READ|FILE_MAP_WRITE|0x00000008u)

#define INVALID_HANDLE_VALUE ((HANDLE)0xffffffffu)
#define INFINITE 0xffffffffu

#define WAIT_OBJECT_0    0x00000000u
#define WAIT_ABANDONED   0x00000080u
#define WAIT_TIMEOUT     0x00000102u
#define WAIT_FAILED      0xffffffffu
#define MAXIMUM_WAIT_OBJECTS 64u

#define EVENT_MODIFY_STATE     0x00000002u
#define EVENT_ALL_ACCESS       (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|EVENT_MODIFY_STATE)
#define MUTEX_MODIFY_STATE     0x00000001u
#define MUTEX_ALL_ACCESS       (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|MUTEX_MODIFY_STATE)
#define SEMAPHORE_MODIFY_STATE 0x00000002u
#define SEMAPHORE_ALL_ACCESS   (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|SEMAPHORE_MODIFY_STATE)
#define TIMER_MODIFY_STATE     0x00000002u
#define TIMER_ALL_ACCESS       (STANDARD_RIGHTS_REQUIRED|SYNCHRONIZE|TIMER_MODIFY_STATE)

#define DUPLICATE_CLOSE_SOURCE 0x00000001u
#define DUPLICATE_SAME_ACCESS  0x00000002u

#define STD_INPUT_HANDLE  ((DWORD)0xfffffff6u)
#define STD_OUTPUT_HANDLE ((DWORD)0xfffffff5u)
#define STD_ERROR_HANDLE  ((DWORD)0xfffffff4u)

#define HANDLE_FLAG_INHERIT            0x00000001u
#define HANDLE_FLAG_PROTECT_FROM_CLOSE 0x00000002u

#define PROCESS_TERMINATE                 0x0001u
#define PROCESS_CREATE_THREAD             0x0002u
#define PROCESS_DUP_HANDLE                0x0040u
#define PROCESS_CREATE_PROCESS            0x0080u
#define PROCESS_QUERY_INFORMATION         0x0400u
#define PROCESS_QUERY_LIMITED_INFORMATION 0x1000u
#define PROCESS_ALL_ACCESS                0x001f1fffu

#define THREAD_TERMINATE          0x0001u
#define THREAD_QUERY_INFORMATION  0x0040u
#define THREAD_ALL_ACCESS         0x001f03ffu

#define TOKEN_ASSIGN_PRIMARY    0x0001u
#define TOKEN_DUPLICATE         0x0002u
#define TOKEN_IMPERSONATE       0x0004u
#define TOKEN_QUERY             0x0008u
#define TOKEN_QUERY_SOURCE      0x0010u
#define TOKEN_ADJUST_PRIVILEGES 0x0020u
#define TOKEN_ADJUST_GROUPS     0x0040u
#define TOKEN_ADJUST_DEFAULT    0x0080u
#define TOKEN_ADJUST_SESSIONID  0x0100u
#define TOKEN_READ              (STANDARD_RIGHTS_READ|TOKEN_QUERY)
#define TOKEN_ALL_ACCESS        (STANDARD_RIGHTS_REQUIRED|TOKEN_ASSIGN_PRIMARY|TOKEN_DUPLICATE|TOKEN_IMPERSONATE|TOKEN_QUERY|TOKEN_QUERY_SOURCE|TOKEN_ADJUST_PRIVILEGES|TOKEN_ADJUST_GROUPS|TOKEN_ADJUST_DEFAULT|TOKEN_ADJUST_SESSIONID)

#define SE_GROUP_MANDATORY          0x00000001u
#define SE_GROUP_ENABLED_BY_DEFAULT 0x00000002u
#define SE_GROUP_ENABLED            0x00000004u
#define SE_GROUP_OWNER              0x00000008u
#define SE_GROUP_USE_FOR_DENY_ONLY  0x00000010u

#ifndef ANYSIZE_ARRAY
#define ANYSIZE_ARRAY 1
#endif

typedef struct _SID_AND_ATTRIBUTES {
    PSID Sid;
    DWORD Attributes;
} SID_AND_ATTRIBUTES, *PSID_AND_ATTRIBUTES;

typedef struct _TOKEN_USER {
    SID_AND_ATTRIBUTES User;
} TOKEN_USER, *PTOKEN_USER;

typedef struct _TOKEN_GROUPS {
    DWORD GroupCount;
    SID_AND_ATTRIBUTES Groups[ANYSIZE_ARRAY];
} TOKEN_GROUPS, *PTOKEN_GROUPS;

typedef struct _LUID {
    DWORD LowPart;
    LONG HighPart;
} LUID, *PLUID;

typedef struct _LUID_AND_ATTRIBUTES {
    LUID Luid;
    DWORD Attributes;
} LUID_AND_ATTRIBUTES, *PLUID_AND_ATTRIBUTES;

typedef struct _TOKEN_PRIVILEGES {
    DWORD PrivilegeCount;
    LUID_AND_ATTRIBUTES Privileges[ANYSIZE_ARRAY];
} TOKEN_PRIVILEGES, *PTOKEN_PRIVILEGES;

typedef enum _TOKEN_INFORMATION_CLASS {
    TokenUser = 1,
    TokenGroups = 2,
    TokenPrivileges = 3,
    TokenOwner = 4,
    TokenPrimaryGroup = 5,
    TokenDefaultDacl = 6
} TOKEN_INFORMATION_CLASS;

typedef struct _TOKEN_OWNER {
    PSID Owner;
} TOKEN_OWNER, *PTOKEN_OWNER;

typedef struct _TOKEN_PRIMARY_GROUP {
    PSID PrimaryGroup;
} TOKEN_PRIMARY_GROUP, *PTOKEN_PRIMARY_GROUP;

typedef struct _TOKEN_DEFAULT_DACL {
    PACL DefaultDacl;
} TOKEN_DEFAULT_DACL, *PTOKEN_DEFAULT_DACL;

#define SE_PRIVILEGE_ENABLED_BY_DEFAULT 0x00000001u
#define SE_PRIVILEGE_ENABLED            0x00000002u
#define SE_PRIVILEGE_REMOVED            0x00000004u
#define SE_PRIVILEGE_USED_FOR_ACCESS    0x80000000u
#define PRIVILEGE_SET_ALL_NECESSARY     0x00000001u

typedef struct _PRIVILEGE_SET {
    DWORD PrivilegeCount;
    DWORD Control;
    LUID_AND_ATTRIBUTES Privilege[ANYSIZE_ARRAY];
} PRIVILEGE_SET, *PPRIVILEGE_SET;

#define STILL_ACTIVE 259u

typedef union _LARGE_INTEGER {
    struct { DWORD LowPart; LONG HighPart; } u;
    long long QuadPart;
} LARGE_INTEGER, *PLARGE_INTEGER;


#ifndef IS_INTRESOURCE
#define IS_INTRESOURCE(_r) ((((ULONG_PTR)(_r)) >> 16) == 0)
#endif
#ifndef MAKEINTRESOURCEA
#define MAKEINTRESOURCEA(i) ((LPSTR)((ULONG_PTR)((WORD)(i))))
#endif
#ifndef MAKEINTRESOURCE
#define MAKEINTRESOURCE MAKEINTRESOURCEA
#endif
#ifndef RT_DIALOG
#define RT_DIALOG MAKEINTRESOURCEA(5)
#endif

typedef struct SECURITY_ATTRIBUTES {
    DWORD nLength;
    LPVOID lpSecurityDescriptor;
    BOOL bInheritHandle;
} SECURITY_ATTRIBUTES, *PSECURITY_ATTRIBUTES, *LPSECURITY_ATTRIBUTES;
